### ISSUE TITLE
More researches

### ISSUE THREAD

**Issue by lawsonjl** [A2Bcorp/RW_A2B_Teleporter#1]
There are lots of research opportunities available here - I've added xml "offset" entries for teleportation time and number of teleportation channels but not implemented them yet. Does anyone have any more ideas?

**Comment by noone57** [comment]
What do you mean by "channels" ?

**Comment by lawsonjl** [comment]
I made an update to the teleporters - since the underground belt system
sort of replaced them in their old role, they sort of needed a new one that
makes them worth the heat and power drawbacks. Teleporters can now be
assigned a "channel" which controls which teleporters are linked together
rather than having them on the same line. A teleporter chooses the closest,
non-busy receiver on the same channel to send items to. Given the expanded
utility, they may need a boost in power consumption or build cost to remain
balanced. Though with the improved definitions system in the newer alphas,
users can configure this much easier so perfect balance isn't necessarily
as important for us to achieve immediately.

**Comment by noone57** [comment]
Awesome !

**Comment by lawsonjl** [comment]
Yeah, I figured it was about time someone knocked out the
teleporter/receiver bug and if I was gonna be tinkering around in there, I
might as well come back with a new feature ;)

**Comment by ForsakenShell** [comment]
It's funny that you did the channel mechanism as I was thinking on how do this myself.  I was going to introduce new components but I think I like your method better.

As to research, each of the new areas need to have a research lists associated with them.  researchHeat, researchPower, researchChannels, etc.

The existing research list needs to be refactored to be more clear as to which it affects (heat).  From there we can expand the research tree.  I'm thinking something along the lines of...
- A2B (base)
  - A2B2 (new components)
    - A2B_Teleport (unlocks teleporter components)
      - A2B_TeleportHeat
      - A2B_TeleportPower
      - A2B_TeleportChannels
      - A2B_TeleportSpeed

**Comment by lawsonjl** [comment]
It's unfortunate that the research menu doesn't have a category system or the like to separate things out, as it would make it a whole lot easier to keep the research list clean... If we let the tree branch out too much at any level, the user's research list gets swamped with entries. As it is, I don't even know if it properly sorts them by name. Perhaps Tynan will add something like that in a later alpha.

That being said, I think the tree you wrote makes the most sense. It's fairly parallel, so it lets the player pick which improvements matter the most to them.

As for how the researches are implemented in the system, I'm thinking moving towards a system where each research is checked individually using the new action hooking system and then deregistering the hook once the research is completed will prevent us from having huge checks going on every tick.

Something like:

``` c#
A2BMonitor.RegisterTickAction("A2B_TeleportHeat", () => {
    if (A2BTeleport.TeleportHeat.isResearched) {
        // adjust the heat situation accordingly
        ...
        A2BMonitor.DeregisterTickAction("A2B_TeleportHeat");
    }
});
```

Keeps it all compartmentalized and simple to debug. Sound good?

**Comment by ForsakenShell** [comment]
That sounds like a good plan.  My initial implementation was really crappy and you're glad I never sent you a copy of the my initial v0.11.0 update.  :P

As to clarity for the users, we can always use my RimSearch tool (on the forums in the tools section) to auto-gen the research tree which we can post in the forum thread and add to the wiki.

**Comment by lawsonjl** [comment]
It seemed to do the job just fine ;)

That sounds neat. We'll definitely need to have the research tree up on the
wiki since it's got a couple stages. It'd be nice to have some kind of
improvement on the ingame presentation of the research system though. I
wonder how difficult it'd be to hook into the UI element and override it...
Probably _too_ difficult.

**Comment by ForsakenShell** [comment]
Actually, replacing the research UI was the next step in my RimSearch project.  I have been busy with A2B, Community Core Library, Advanced Mining (Skyrim), etc, etc, etc to get to that stage though.

I was going to look into how EdB hooks and replaces the UI to redo the research screen using machine generated xml from the RimSearch tool which would create the placement info.  All that is unrelated to A2B, however.

Ma plate!  Iz-a tew fulllll!

**Comment by lawsonjl** [comment]
I believe they completely replace the UI with their own controls and load it up through Unity in the same way the base game does it. A research screen replacement would either want a less... exhaustive solution or would be more at home within the EdB project itself.

It's too bad I can't get bytecode manipulation running in C#. I'd totally set up a ForgeHooks like situation for this game.

I agree though. It's tangentially related to A2B at best.

**Comment by ForsakenShell** [comment]
This issue seems fairly well resolved.  Closing.
